/* EmailBriefing.jsx — "Send Briefing" composer (exported to window.EmailBriefing)
   Auto-summarises the live dashboard findings into an email to the sales /
   ad-strategy team, with recommended next steps. Sending is mocked here
   (logs to the Overmind terminal) — see EMAIL_BRIEFING.md to wire a real send. */
const { useState: useSE, useMemo: useME } = React;

/* derive a structured briefing from the live data layer */
function buildBriefing() {
  const D = window.ADTEC;
  const movers = [...D.trends].sort((a, b) => b.growth - a.growth);
  const top = movers.slice(0, 3);
  const decliner = movers[movers.length - 1];
  const leak = D.kpiRows.find((r) => r.tone === "warn");
  const topQ = D.aiQueries[0];
  const ba = Object.fromEntries(D.beforeAfter.map((r) => [r.k, r]));
  const ltv = D.advKpis.find((k) => k.id === "ltvcac");

  const findings = [
    `“${top[0].kw}” is the top mover — up ${top[0].growth}% this week (${top[0].vol} mentions).`,
    `Other rising signals: ${top.slice(1).map((t) => `${t.kw} (+${t.growth}%)`).join(", ")}.`,
    `Most-asked AI question right now: “${topQ.q}” — ${topQ.intent.toLowerCase()} intent.`,
    leak ? `Funnel risk: ${leak.v} ${leak.b.replace(/^[⚠↓↑]\s*/, "")}.` : null,
    `Performance is trending up: CPL ${ba.CPL ? ba.CPL.delta : "−20%"}, leads ${ba.Leads ? ba.Leads.delta : "+40%"}, ROAS ${ba.ROAS ? ba.ROAS.delta : "+35%"}.`,
    ltv ? `Unit economics healthy — LTV:CAC at ${ltv.value} (${ltv.sub}).` : null,
  ].filter(Boolean);

  const nextSteps = [
    `Adopt the Optimistic budget plan — target 14,230 leads at £4.20 CPL (on-budget at £62,400).`,
    `Push fresh creative on “${top[0].kw}” while it's peaking — Spark Ads (TikTok) + Advantage+ (Meta).`,
    leak ? `Plug the ${leak.b.replace(/^[⚠↓↑]\s*/, "")} with a retargeting layer — this already cut cart abandonment 6.9pt.` : null,
    `Trim spend on the cooling term “${decliner.kw}” (${decliner.growth}%) and reallocate to the movers above.`,
    `Pre-brief creative + sales on the next drop so we're ready when search volume spikes.`,
  ].filter(Boolean);

  const subject = `Weekly Ad Intelligence Briefing — ${top[0].kw} +${top[0].growth}%, CPL down 20%`;
  return { findings, nextSteps, subject, top };
}

function toPlainText(b, recipients) {
  return [
    `To: ${recipients.join(", ")}`,
    `Subject: ${b.subject}`,
    ``,
    `Team,`,
    ``,
    `Here's this week's market & campaign read-out from the SIGNAL dashboard.`,
    ``,
    `KEY FINDINGS`,
    ...b.findings.map((f) => `  • ${f}`),
    ``,
    `HOW WE PROCEED`,
    ...b.nextSteps.map((s, i) => `  ${i + 1}. ${s}`),
    ``,
    `Full live dashboard: signal.app/intelligence`,
    `— Generated by SIGNAL · Overmind agent`,
  ].join("\n");
}

function Field({ label, children }) {
  return (
    <div style={{ display: "flex", alignItems: "flex-start", gap: 12, padding: "9px 0", borderBottom: "1px solid #161616" }}>
      <span className="eyebrow" style={{ width: 64, flex: "none", paddingTop: 4 }}>{label}</span>
      <div style={{ flex: 1, minWidth: 0 }}>{children}</div>
    </div>
  );
}

function EmailBriefing({ onClose }) {
  const b = useME(() => buildBriefing(), []);
  const [recipients, setRecipients] = useSE(["ad-strategy@gymshark.com", "sales@gymshark.com", "growth-lead@gymshark.com"]);
  const [subject, setSubject] = useSE(b.subject);
  const [note, setNote] = useSE("");
  const [newRcpt, setNewRcpt] = useSE("");
  const [sent, setSent] = useSE(false);
  const [sending, setSending] = useSE(false);

  const addRcpt = () => {
    const v = newRcpt.trim();
    if (v && /\S+@\S+/.test(v) && !recipients.includes(v)) { setRecipients((r) => [...r, v]); setNewRcpt(""); }
  };
  const copy = () => navigator.clipboard && navigator.clipboard.writeText(toPlainText({ ...b, subject }, recipients));

  const send = async () => {
    if (sending || sent) return;
    const base = window.__ADTEC_API_BASE || "";
    const payload = {
      client_id: window.__ADTEC_CLIENT_ID || "gymshark",
      to: recipients, subject,
      body: toPlainText({ ...b, subject }, recipients) + (note ? `\n\nNote: ${note}` : ""),
      findings: b.findings, next_steps: b.nextSteps,
    };
    setSending(true);
    window.adtecLog && window.adtecLog([{ msg: `Routing the briefing through Overmind for ${recipients.length} recipients…`, tone: "work" }]);
    try {
      if (!base) throw new Error("no backend configured");
      const res = await fetch(base + "/api/v1/agents/send-briefing", {
        method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (data.trace) window.adtecLog && window.adtecLog(data.trace);   // replay the real Overmind span
      if (!data.sent) throw new Error(data.error || "send failed");
      setSent(true); setTimeout(onClose, 1900);
    } catch (e) {
      // offline / prototype fallback — simulate the Overmind round-trip locally
      window.adtecLog && window.adtecLog([
        { msg: "Claude refined the briefing copy.", tone: "ok" },
        { msg: "Briefing delivered to the sales & ad-strategy team.", tone: "ok" },
        { msg: "Overmind span closed · score 0.96.", tone: "info" },
      ]);
      setSent(true); setTimeout(onClose, 1900);
    } finally { setSending(false); }
  };

  return (
    <div style={{ position: "fixed", inset: 0, zIndex: 200, display: "flex", alignItems: "center", justifyContent: "center", padding: 24 }}>
      <div onClick={onClose} style={{ position: "absolute", inset: 0, background: "rgba(0,0,0,.66)", backdropFilter: "blur(2px)" }}></div>
      <div style={{ position: "relative", width: "min(720px, 96vw)", maxHeight: "88vh", display: "flex", flexDirection: "column",
        background: "#0A0A0A", border: "1px solid #2A2A2A", borderRadius: 4, boxShadow: "0 24px 80px rgba(0,0,0,.7)",
        animation: "briefIn .22s cubic-bezier(.3,0,.2,1)" }}>
        {/* header */}
        <div style={{ flex: "none", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 18px", borderBottom: "1px solid #1F1F1F" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <span style={{ color: "#00D4FF", fontSize: 15 }}>✉</span>
            <span style={{ fontFamily: "var(--disp)", fontWeight: 700, fontSize: 18, textTransform: "uppercase", color: "#fff", letterSpacing: ".01em" }}>Send Briefing</span>
            <span className="eyebrow" style={{ marginTop: 2 }}>· auto-summarised from live findings</span>
          </div>
          <button onClick={onClose} style={{ background: "none", border: "1px solid #2A2A2A", color: "#888", cursor: "pointer", width: 24, height: 24, borderRadius: 12, fontSize: 12 }}>✕</button>
        </div>

        {/* meta + body */}
        <div style={{ flex: 1, overflowY: "auto", padding: "4px 18px 14px" }}>
          <Field label="TO">
            <div style={{ display: "flex", flexWrap: "wrap", gap: 6, alignItems: "center" }}>
              {recipients.map((r) => (
                <span key={r} className="pill" style={{ background: "#111", border: "1px solid #2A2A2A", color: "#CFCFCF", fontSize: 11 }}>
                  {r}
                  <span onClick={() => setRecipients((x) => x.filter((y) => y !== r))} style={{ cursor: "pointer", color: "#666", marginLeft: 2 }}>✕</span>
                </span>
              ))}
              <input value={newRcpt} onChange={(e) => setNewRcpt(e.target.value)} onKeyDown={(e) => e.key === "Enter" && addRcpt()}
                placeholder="add email…" style={inp} />
            </div>
          </Field>
          <Field label="SUBJECT">
            <input value={subject} onChange={(e) => setSubject(e.target.value)} style={{ ...inp, width: "100%", color: "#fff", fontSize: 13 }} />
          </Field>

          {/* generated body */}
          <div style={{ paddingTop: 14, fontFamily: "var(--mono)", fontSize: 12.5, lineHeight: 1.6, color: "#D6D6D6" }}>
            <p style={{ margin: "0 0 12px" }}>Team,</p>
            <p style={{ margin: "0 0 16px", color: "#A8A8A8" }}>Here's this week's market &amp; campaign read-out from the SIGNAL dashboard.</p>

            <div className="eyebrow" style={{ color: "#00D4FF", marginBottom: 8 }}>Key Findings</div>
            <ul style={ul}>
              {b.findings.map((f, i) => <li key={i} style={li}><span style={{ color: "#00FF88", marginRight: 8 }}>›</span>{f}</li>)}
            </ul>

            <div className="eyebrow" style={{ color: "#00D4FF", margin: "18px 0 8px" }}>How We Proceed</div>
            <ol style={{ ...ul, counterReset: "step" }}>
              {b.nextSteps.map((s, i) => (
                <li key={i} style={li}><span className="tnum" style={{ color: "#FFB800", marginRight: 8, flex: "none" }}>{String(i + 1).padStart(2, "0")}</span>{s}</li>
              ))}
            </ol>

            <div className="eyebrow" style={{ color: "#666", margin: "18px 0 6px" }}>Add a note (optional)</div>
            <textarea value={note} onChange={(e) => setNote(e.target.value)} rows={2} placeholder="Anything to add before this goes out…"
              style={{ ...inp, width: "100%", resize: "vertical", lineHeight: 1.5, color: "#E2E2E2" }} />

            <p style={{ margin: "16px 0 0", color: "#555", fontSize: 11 }}>Full live dashboard: signal.app/intelligence · Generated by SIGNAL · Overmind agent</p>
          </div>
        </div>

        {/* footer */}
        <div style={{ flex: "none", display: "flex", alignItems: "center", gap: 10, padding: "12px 18px", borderTop: "1px solid #1F1F1F" }}>
          <span style={{ fontSize: 10.5, color: "#666", fontFamily: "var(--mono)" }}>
            {sent ? <span style={{ color: "#00FF88" }}>✓ Sent to {recipients.length} recipients via Overmind</span>
                  : sending ? <span style={{ color: "#00D4FF" }}>Processing through Overmind…</span>
                  : `Ready to send to ${recipients.length} recipient${recipients.length === 1 ? "" : "s"}`}
          </span>
          <div style={{ marginLeft: "auto", display: "flex", gap: 8 }}>
            <button className="btn" onClick={copy}>COPY TEXT</button>
            <button className="btn" onClick={onClose}>CANCEL</button>
            <button className="btn btn-primary" onClick={send} disabled={sent || sending || recipients.length === 0}
              style={{ opacity: sent || sending || recipients.length === 0 ? .5 : 1 }}>
              {sent ? "SENT ✓" : sending ? "SENDING…" : "SEND BRIEFING ↗"}
            </button>
          </div>
        </div>
      </div>
      <style>{`@keyframes briefIn{from{opacity:0;transform:translateY(12px) scale(.99)}to{opacity:1;transform:none}}`}</style>
    </div>
  );
}

const inp = { background: "transparent", border: "none", outline: "none", color: "#CFCFCF",
  fontFamily: "var(--mono)", fontSize: 12, padding: "4px 2px" };
const ul = { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 7 };
const li = { display: "flex", alignItems: "flex-start" };

window.EmailBriefing = EmailBriefing;
